import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from torch.utils.data import TensorDataset, DataLoader, random_split


# =========================
# 1. Oscillator definition
# =========================
class Oscillator:
    def __init__(self, theta, omega, amplitude=1.0):
        self.theta = theta
        self.omega = omega
        self.amplitude = amplitude

    def step(self, dt):
        dtheta = self.omega
        self.theta += dtheta * dt

    def get_position(self):
        return self.amplitude * np.sin(self.theta)


# =========================
# 2. Simulation
# =========================
def simulate_single(theta0, omega, steps, dt):
    osc = Oscillator(theta0, omega)

    theta_hist = []
    pos_hist = []

    for _ in range(steps):
        theta_hist.append(osc.theta)
        pos_hist.append(osc.get_position())
        osc.step(dt)

    return np.array(theta_hist), np.array(pos_hist)


# =========================
# 3. Dataset creation
# =========================
def create_phase_conditioned_dataset(
    num_trajectories=200,
    steps=300,
    dt=0.01,
    horizon=20,
    omega_range=(0.5, 2.0),
    phase_error_range=(-1.0, 1.0),
    seed=42,
):
    """
    Creates supervised data with phase-error conditioning.

    Input:
        [x_t, theta_t, omega, phase_error]

    Target:
        future sequence of shape (horizon, 2), where each step is [x, theta]

    The target trajectory is generated by shifting the future phase by phase_error:
        theta_future_shifted = theta_future + phase_error
        x_future_shifted = sin(theta_future_shifted)

    This teaches the model:
        "given the current state and desired phase offset, predict the adjusted future motion"
    """
    rng = np.random.default_rng(seed)

    X_all = []
    Y_all = []

    for _ in range(num_trajectories):
        theta0 = rng.uniform(0.0, 2.0 * np.pi)
        omega = rng.uniform(*omega_range)

        theta_hist, pos_hist = simulate_single(theta0, omega, steps, dt)

        for t in range(steps - horizon):
            x_t = pos_hist[t]
            theta_t = theta_hist[t]

            # sample desired phase offset / phase correction
            phase_error = rng.uniform(*phase_error_range)
            theta_target = theta_t + phase_error

            # input: current motion state + desired timing correction
            X_all.append([x_t, theta_t, omega, phase_error])

            # future nominal trajectory
            future_theta = theta_hist[t + 1 : t + 1 + horizon]

            # shifted future trajectory (conditioned target)
            future_theta_shifted = future_theta + phase_error
            future_x_shifted = np.sin(future_theta_shifted)

            Y_all.append(np.stack([future_x_shifted, future_theta_shifted], axis=1))

    X = np.array(X_all, dtype=np.float32)
    Y = np.array(Y_all, dtype=np.float32)

    return X, Y


# =========================
# 4. Model
# =========================
class PhaseConditionedMLP(nn.Module):
    def __init__(self, input_dim=4, hidden_dim=64, horizon=20):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, horizon * 2)
        )

    def forward(self, x):
        return self.net(x)


# =========================
# 5. Prepare dataloaders
# =========================
def prepare_dataloaders(X, Y, batch_size=128, val_ratio=0.2, seed=42):
    Y = Y.reshape(Y.shape[0], -1)  # (N, H, 2) -> (N, H*2)

    X_tensor = torch.tensor(X, dtype=torch.float32)
    Y_tensor = torch.tensor(Y, dtype=torch.float32)

    dataset = TensorDataset(X_tensor, Y_tensor)

    val_size = int(len(dataset) * val_ratio)
    train_size = len(dataset) - val_size

    generator = torch.Generator().manual_seed(seed)
    train_dataset, val_dataset = random_split(
        dataset,
        [train_size, val_size],
        generator=generator
    )

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

    return train_loader, val_loader, Y.shape[1] // 2


# =========================
# 6. Validation loss
# =========================
def compute_validation_loss(model, val_loader, loss_fn, device):
    model.eval()
    total_loss = 0.0
    total_samples = 0

    with torch.no_grad():
        for x_batch, y_batch in val_loader:
            x_batch = x_batch.to(device)
            y_batch = y_batch.to(device)

            pred = model(x_batch)
            loss = loss_fn(pred, y_batch)

            batch_size = x_batch.size(0)
            total_loss += loss.item() * batch_size
            total_samples += batch_size

    return total_loss / total_samples


# =========================
# 7. Training
# =========================
def train_model(
    train_loader,
    val_loader,
    horizon,
    epochs=30,
    lr=1e-3,
    hidden_dim=64,
    model_path="best_phase_conditioned_mlp.pth"
):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = PhaseConditionedMLP(
        input_dim=4,
        hidden_dim=hidden_dim,
        horizon=horizon
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.MSELoss()

    best_val_loss = float("inf")
    train_losses = []
    val_losses = []

    for epoch in range(epochs):
        model.train()
        total_train_loss = 0.0
        total_train_samples = 0

        for x_batch, y_batch in train_loader:
            x_batch = x_batch.to(device)
            y_batch = y_batch.to(device)

            pred = model(x_batch)
            loss = loss_fn(pred, y_batch)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            batch_size = x_batch.size(0)
            total_train_loss += loss.item() * batch_size
            total_train_samples += batch_size

        avg_train_loss = total_train_loss / total_train_samples
        avg_val_loss = compute_validation_loss(model, val_loader, loss_fn, device)

        train_losses.append(avg_train_loss)
        val_losses.append(avg_val_loss)

        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            torch.save(model.state_dict(), model_path)
            saved_msg = " <-- saved best model"
        else:
            saved_msg = ""

        print(
            f"Epoch {epoch+1:02d}/{epochs} | "
            f"train loss: {avg_train_loss:.6f} | "
            f"val loss: {avg_val_loss:.6f}{saved_msg}"
        )

    print(f"\nBest validation loss: {best_val_loss:.6f}")
    print(f"Best model saved to: {model_path}")

    return model, train_losses, val_losses


# =========================
# 8. Plot losses
# =========================
def plot_losses(train_losses, val_losses):
    plt.figure()
    plt.plot(train_losses, label="train loss")
    plt.plot(val_losses, label="validation loss")
    plt.xlabel("Epoch")
    plt.ylabel("MSE Loss")
    plt.title("Training and Validation Loss")
    plt.legend()
    plt.show()


# =========================
# 9. Evaluate saved model
# =========================
def evaluate_best_model(model_path, X, Y):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    horizon = Y.shape[1]

    model = PhaseConditionedMLP(input_dim=4, hidden_dim=64, horizon=horizon).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    i = np.random.randint(0, len(X))

    x_input = torch.tensor(X[i:i+1], dtype=torch.float32).to(device)
    y_true = Y[i]  # shape: (horizon, 2)

    with torch.no_grad():
        y_pred = model(x_input).cpu().numpy().reshape(horizon, 2)

    phase_error = X[i, 3]
    print(f"Example phase_error = {phase_error:.4f}")

    plt.figure()
    plt.plot(y_true[:, 0], label="true x")
    plt.plot(y_pred[:, 0], label="pred x")
    plt.legend()
    plt.title("Position Prediction")
    plt.show()

    plt.figure()
    plt.plot(y_true[:, 1], label="true theta")
    plt.plot(y_pred[:, 1], label="pred theta")
    plt.legend()
    plt.title("Phase Prediction")
    plt.show()


# =========================
# 10. Compare different phase errors
# =========================
def test_phase_error_response(model_path, base_x, base_theta, base_omega, horizon=20):
    """
    Show how the predicted future changes when phase_error changes.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = PhaseConditionedMLP(input_dim=4, hidden_dim=64, horizon=horizon).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    phase_errors = [-0.8, -0.4, 0.0, 0.4, 0.8]

    plt.figure()
    for pe in phase_errors:
        inp = torch.tensor([[base_x, base_theta, base_omega, pe]], dtype=torch.float32).to(device)

        with torch.no_grad():
            pred = model(inp).cpu().numpy().reshape(horizon, 2)

        plt.plot(pred[:, 0], label=f"phase_error={pe}")

    plt.xlabel("Future step")
    plt.ylabel("Predicted x")
    plt.title("Predicted Position under Different Phase Errors")
    plt.legend()
    plt.show()


# =========================
# 11. Main
# =========================
def main():
    print("Generating phase-conditioned dataset...")
    X, Y = create_phase_conditioned_dataset(
        num_trajectories=200,
        steps=300,
        dt=0.01,
        horizon=20,
        omega_range=(0.5, 2.0),
        phase_error_range=(-1.0, 1.0),
        seed=42,
    )

    print("X shape:", X.shape)   # (N, 4)
    print("Y shape:", Y.shape)   # (N, horizon, 2)

    print("\nPreparing train/validation split...")
    train_loader, val_loader, horizon = prepare_dataloaders(
        X, Y, batch_size=128, val_ratio=0.2, seed=42
    )

    print("\nTraining model...")
    _, train_losses, val_losses = train_model(
        train_loader=train_loader,
        val_loader=val_loader,
        horizon=horizon,
        epochs=30,
        lr=1e-3,
        hidden_dim=64,
        model_path="best_phase_conditioned_mlp.pth"
    )

    print("\nPlotting losses...")
    plot_losses(train_losses, val_losses)

    print("\nEvaluating saved best model...")
    evaluate_best_model("best_phase_conditioned_mlp.pth", X, Y)

    print("\nTesting response to different phase errors...")
    base_idx = np.random.randint(0, len(X))
    base_x, base_theta, base_omega, _ = X[base_idx]
    test_phase_error_response(
        "best_phase_conditioned_mlp.pth",
        base_x=base_x,
        base_theta=base_theta,
        base_omega=base_omega,
        horizon=horizon
    )


if __name__ == "__main__":
    main()